services:
  spring-app:
    image: hex-app:${APP_VERSION}
    build: .
    container_name: spring-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: ${DATA_SOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATA_SOURCE_USER}
      SPRING_DATASOURCE_PASSWORD: ${DATA_SOURCE_PASSWORD}
      PORT: ${PORT}
    ports:
      - "${PORT}:8080"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  jenkins_home:
